name: Update BKX Data Live

on:
  workflow_dispatch:         # Allows manual run from the Actions tab

permissions:
  contents: write            # Allows GitHub Actions to commit changes back to the repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run data update script
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: python bkx_update_live.py

      - name: Commit and push updated bkx_data.csv
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add bkx_data.csv
          git diff --cached --quiet || git commit -m "Auto-update BKX data"
          git push